version: "3"

services:

  mockserver:
    image: jamesdbloom/mockserver:mockserver-5.7.2
    container_name: mockserver
    ports:
      - "1080:1080"

  selenium-hub:
    image: selenium/hub:3.141
    container_name: selenium-hub
    ports:
      - "4444:4444"
    expose:
      - 4444

  chrome:
    image: selenium/node-chrome:3.141
    container_name: chrome
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444

  firefox:
    image: selenium/node-firefox:3.141
    container_name: firefox
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
