os: linux

dist: xenial

language: java

jdk:
  - openjdk8

services:
  - docker

cache:
  directories:
    - "$HOME/.cache"

addons:
  artifacts:
    working_dir: reports/ExtentReport.html

before_install:
  - docker-compose up --build -d

script: |
  mvn -B clean test \
  -Dselenide.remote=http://0.0.0.0:4444/wd/hub \
  -Dlistener=io/company/utils/listeners/ExtentReportListener.java
