name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Validate
        run: mvn -B validate
      - name: Build the docker-compose stack
        run: docker-compose up -d
      - name: Waiting containers
        uses: jakejarvis/wait-action@master
        with:
          time: '60s'
      - name: Check running containers
        run: docker ps
      - name: Run tests
        run: |
          mvn -B test \
          -Dselenide.remote=http://0.0.0.0:4444/wd/hub \
          -Dmock.server.address=0.0.0.0:3000 \
          -Dlistener=utils/listeners/MockServerListener.java,utils/listeners/ExtentReportListener.java
      - name: Publish reports
        uses: actions/upload-artifact@v1
        with:
          name: extent-report
          path: reports/ExtentReport.html
