name: release-candidate

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Compile
        run: mvn -B -f ui-tests/pom.xml compile

      - name: Lint
        run: mvn -B -f ui-tests/pom.xml validate

      - name: Initialize containers
        run: docker-compose -f selenium-grid/docker-compose.yml up -d

      - name: Wait containers
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'

      - name: Check available containers
        run: docker ps

      - name: Tests
        run: |
          mvn -B clean test \
            -f ui-tests/pom.xml \
            -Dselenide.proxyEnabled=true \
            -Dselenide.headless=true \
            -Dselenide.remote=http://0.0.0.0:4444/wd/hub \
            -Dlistener=io/company/utils/listeners/MockListener.java
