name: release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Initialize containers
        run: docker-compose up -d

      - name: Wait containers
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'

      - name: Check available containers
        run: docker ps

      - name: Install gpg secret key
        run: |
          echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}" | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG

      - name: Deploy archetype
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        run: |
          mvn -B clean deploy \
          -Dgpg.passphrase=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
